# Week 9 Assignment: Tidying & Transforming Data
## DOWNLOADING THE DATA FROM GITHUB FILE
### by Olga Kriyokov

In [2]:
#importing pandas
import pandas as pd
#github url
url="https://raw.githubusercontent.com/kaolga28/DAV-54000/master/Data_week9assignment.csv"
#data reading
data=pd.read_csv(url)
#printing the data 
data

Unnamed: 0 Unnamed: 1  Los Angeles  Phoenix  San Diego  San Fransisco  \
0     ALASKA    on time        497.0    221.0      212.0          503.0   
1        NaN    delayed         62.0     12.0       20.0          105.0   
2        NaN        NaN          NaN      NaN        NaN            NaN   
3    AM WEST    on time        694.0   4840.0      383.0          320.0   
4        NaN    delayed        117.0    415.0       65.0          129.0   

   Seattle  
0   1841.0  
1    305.0  
2      NaN  
3    201.0  
4     61.0

As you can see, the data contains NAN rows that needs to be removed for the long format

In [3]:
#dropping row where all nans
data = data.dropna(how='all')
#printing data
data

Unnamed: 0 Unnamed: 1  Los Angeles  Phoenix  San Diego  San Fransisco  \
0     ALASKA    on time        497.0    221.0      212.0          503.0   
1        NaN    delayed         62.0     12.0       20.0          105.0   
3    AM WEST    on time        694.0   4840.0      383.0          320.0   
4        NaN    delayed        117.0    415.0       65.0          129.0   

   Seattle  
0   1841.0  
1    305.0  
3    201.0  
4     61.0

## THE DATA CONTAINS NAN THAT ARE NEEDED TO BE FILLED FOR LONG FORMAT
### FILING NAN AND GIVING COLUMNS THERE NAME

In [4]:
#remove setting_copy warning
import warnings
warnings.filterwarnings("ignore")
#Renaming unnamed columns
data.rename( columns={'Unnamed: 0':'AIRLINE'}, inplace=True, copy=False )
data.rename( columns={'Unnamed: 1':'ARRIVAL'}, inplace=True,copy=False )
#Filling NANS as required
data['AIRLINE'].iloc[1]="ALASKA"
data['AIRLINE'].iloc[3]="AM WEST"
#Reseting the indexes for before further process
data.reset_index(drop=True,inplace=True)
#printing data
data

AIRLINE  ARRIVAL  Los Angeles  Phoenix  San Diego  San Fransisco  Seattle
0   ALASKA  on time        497.0    221.0      212.0          503.0   1841.0
1   ALASKA  delayed         62.0     12.0       20.0          105.0    305.0
2  AM WEST  on time        694.0   4840.0      383.0          320.0    201.0
3  AM WEST  delayed        117.0    415.0       65.0          129.0     61.0

## Data in long format
## Analysis

## Which airline had the best overall on time performance?

In [4]:
Total=data.sum(axis = 1) 
Alaska_Total=Total[0]+Total[1]
print ("Alaska Total flights: ",Alaska_Total)
Alaska_Ratio=Total[0]/Alaska_Total
print ("Alaska ON TIME ratio: ",Alaska_Ratio)
AM_WEST_Total=Total[2]+Total[3]
print ("AM WEST Total flights: ",AM_WEST_Total)
AM_WEST_Ratio=Total[2]/AM_WEST_Total
print ("AM WEST ON TIME ratio: ",AM_WEST_Ratio)

Alaska Total flights:  3778.0
Alaska ON TIME ratio:  0.8665960825833775
AM WEST Total flights:  7225.0
AM WEST ON TIME ratio:  0.8910726643598615


The results show that Alaska's flights have more probability of getting delayed with 86% comparing to AM West with 89%

## Which airline had the best overall on time performance for respective cities?

In [5]:
#City wise performance on time performance
cities=['Los Angeles','Phoenix','San Diego','San Fransisco','Seattle']
AM_WEST=[]
Alaska=[]
for rows in cities:
    city_data=data[rows]
    Alaska_Total=city_data[0]+city_data[1]
    Alaska_Ratio=city_data[0]/Alaska_Total
    AM_WEST_Total=city_data[2]+city_data[3]
    AM_WEST_Ratio=city_data[2]/AM_WEST_Total
    print ("Alaska ON TIME ratio for ",rows,": ",Alaska_Ratio)
    print ("AM WEST ON TIME ratio for ",rows,": ",AM_WEST_Ratio)
    if (Alaska_Ratio>AM_WEST_Ratio):
        Alaska.append(rows)
    else:
        AM_WEST.append(rows)
print ("Cities having better on time ratio for Alaska: ",Alaska)
print ("Cities having better on time ratio for AM_WEST: ",AM_WEST)

Alaska ON TIME ratio for  Los Angeles :  0.889087656529517
AM WEST ON TIME ratio for  Los Angeles :  0.8557336621454994
Alaska ON TIME ratio for  Phoenix :  0.9484978540772532
AM WEST ON TIME ratio for  Phoenix :  0.9210275927687916
Alaska ON TIME ratio for  San Diego :  0.9137931034482759
AM WEST ON TIME ratio for  San Diego :  0.8549107142857143
Alaska ON TIME ratio for  San Fransisco :  0.8273026315789473
AM WEST ON TIME ratio for  San Fransisco :  0.7126948775055679
Alaska ON TIME ratio for  Seattle :  0.8578751164958062
AM WEST ON TIME ratio for  Seattle :  0.767175572519084
Cities having better on time ratio for Alaska:  ['Los Angeles', 'Phoenix', 'San Diego', 'San Fransisco', 'Seattle']
Cities having better on time ratio for AM_WEST:  []


In [6]:
#City wise performance on no of flights
cities=['Los Angeles','Phoenix','San Diego','San Fransisco','Seattle']
AM_WEST=[]
Alaska=[]
for rows in cities:
    city_data=data[rows]
    Alaska_Total=city_data[0]+city_data[1]
    AM_WEST_Total=city_data[2]+city_data[3]
    print ("Alaska flights from ",rows,": ",Alaska_Total)
    print ("AM WEST flights from ",rows,": ",AM_WEST_Total)
    if (Alaska_Total>AM_WEST_Total):
        Alaska.append(rows)
    else:
        AM_WEST.append(rows)
print ("Cities having more flights from Alaska: ",Alaska)
print ("Cities having more flights from AM_WEST: ",AM_WEST)

Alaska flights from  Los Angeles :  559.0
AM WEST flights from  Los Angeles :  811.0
Alaska flights from  Phoenix :  233.0
AM WEST flights from  Phoenix :  5255.0
Alaska flights from  San Diego :  232.0
AM WEST flights from  San Diego :  448.0
Alaska flights from  San Fransisco :  608.0
AM WEST flights from  San Fransisco :  449.0
Alaska flights from  Seattle :  2146.0
AM WEST flights from  Seattle :  262.0
Cities having more flights from Alaska:  ['San Fransisco', 'Seattle']
Cities having more flights from AM_WEST:  ['Los Angeles', 'Phoenix', 'San Diego']


The results shows the greater number of flights with respect to airline

Wide format: I wrote the data as a combination of on time and delayed parameters:

In [7]:
first=["Los Angeles","Phoenix","San Diego","San Fransisco","Seattle"]
second=[497,62],[221,12],[212,20],[503,105],[1841,305]
third=[694,117],[4840,415],[383,65],[320,129],[201,61]
df=pd.DataFrame()
df['Airline']=first
df['Alaska']=second
df['AM_WEST']=third
df=df.transpose()
print ("Wide data frame \n",df)

Wide data frame 
                    0            1          2              3            4
Airline  Los Angeles      Phoenix  San Diego  San Fransisco      Seattle
Alaska     (497, 62)    (221, 12)  (212, 20)     (503, 105)  (1841, 305)
AM_WEST   (694, 117)  (4840, 415)  (383, 65)     (320, 129)    (201, 61)


As you can see from the analysis above, Alaska airlines, flights from Seattle had 1841 delays, and AM_WEST had 4840 delays for flights from Phoenix.  